---
title: "Rscript GSEA Pathway Analysis MD"
output: html_document
date: "2023-03-03"
editor_options: 
  chunk_output_type: console
---

```{r}
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("fgsea")
BiocManager::install("data.table")
BiocManager::install("ggplot2")
BiocManager::install("tidyverse")
BiocManager::install("readr")
BiocManager::install("tibble")
BiocManager::install("dplyr")
instal.packages("digest")
install.packages("openxlsx")
```

```{r}
library(fgsea)
library(data.table)
library(ggplot2)
library(tidyverse)
library(readr)
library(tibble)
library(dplyr)
library(digest)

#packageVersion("fGSEA")
```

Load the metadata and rawcount.csv file

```{r}
setwd("G:/My Drive/RNAseq/Carli_SN+LUVA")
#RNA_project <- readline(prompt="Project code: ") #enter projectcode until second dash
Cell1_name <- readline(prompt="Name cell type 1: ")
Cell2_name <- readline(prompt="Name cell type 2: ")

metadata_Cell1 <- read.csv(file.path("analyse", paste0("Metadata", Cell1_name, ".csv")), row.names = 1)
metadata_Cell2 <- read.csv(file.path("analyse", paste0("Metadata", Cell2_name, ".csv")), row.names = 1)

counts_Cell1 <- read.csv(file.path("analyse", paste0("Rawcounts", Cell1_name, ".csv")), row.names = 1)
counts_Cell2 <- read.csv(file.path("analyse", paste0("Rawcounts", Cell2_name, ".csv")), row.names = 1)
```

Load comparison dataset (all genes)

```{r}
Cell1_sig_DEGs <- read.csv(file.path("analyse" , paste0("ID", Cell1_name, ".csv")), sep = ",", row.names = 1)
Cell1_sig_DEGs <- rownames_to_column(Cell1_sig_DEGs, "Symbol")

Cell2_sig_DEGs <- read.csv(file.path("analyse" , paste0("ID", Cell2_name, ".csv")), sep = ";", row.names = 1)
Cell2_sig_DEGs <- rownames_to_column(Cell2_sig_DEGs, "Symbol")
```

Select columns

```{r}
#Cell1_stat <- Cell1_sig_DEGs %>% select(1, stat)
#Cell1_ranks <- deframe(Cell1_stat)
#head(Cell1_ranks, 20)

# Old code above removed gene names from Cell1_ranks, below keeps both statistics and gene names
# Extract the statistics column from Cell1_stat
stats <- Cell1_stat$stat
# Use the row names of Cell1_stat as names for the statistics
Cell1_ranks <- stats
names(Cell1_ranks) <- rownames(Cell1_stat)

#Cell2_stat <- Cell2_sig_DEGs %>% select(1, stat) #check if co vs mono
#Cell2_ranks <- deframe(Cell2_stat)
#head(Cell2_ranks, 20)
```

Load the pathways

```{r}
H_pathways <- gmtPathways("GSEA/h.all.v2023.1.Hs.symbols.gmt")
c2CP_pathways <- gmtPathways("GSEA/c2.cp.v2023.1.Hs.symbols.gmt")
c5BP_pathways <- gmtPathways("GSEA/c5.go.bp.v2023.1.Hs.symbols.gmt")
c7IM_pathways <- gmtPathways("GSEA/c7.all.v2023.2.Hs.symbols.gmt")
Th2_GO_pathway <- gmtPathways("GSEA/Th2 analysis/Th2GO_genes.gmt")
Th2_pathway <- gmtPathways("GSEA/Th2 analysis/Th2_genes.gmt")
SNP_asthma_pathway <- gmtPathways("GSEA/Asthma Genes/Zaid signature.gmt")
```

Show the first few pathways, and within those, show only the first few genes

```{r}
H_pathways %>%
  head() %>%
  lapply(head)
c2CP_pathways %>%
  head() %>%
  lapply(head)
c5BP_pathways %>% #change names of pathways everywheree!!
  head() %>%
  lapply(head)
c7IM_pathways %>% #change names of pathways everywheree!!
  head() %>%
  lapply(head)
```

Run the FGSEA

```{r}
fgsea_H_Cell1 <- fgsea(pathways = H_pathways,
                  stats = Cell1_ranks,
                  minSize  = 15,
                  maxSize  = 500,
                  nperm = 1000)
#fgsea_H_Cell2 <- fgsea(pathways = H_pathways,
#                  stats = Cell2_ranks,
#                  minSize  = 15,
#                  maxSize  = 500,
#                  nperm = 1000)

fgsea_c2CP_Cell1 <- fgsea(pathways = c2CP_pathways,
                          stats = Cell1_ranks,
                          minSize  = 15,
                          maxSize  = 500,
                          nperm = 1000)
#fgsea_c2CP_Cell2 <- fgsea(pathways = c2CP_pathways,
#                          stats = Cell2_ranks,
#                          minSize  = 15,
#                          maxSize  = 500,
#                          nperm = 1000)

fgsea_c5BP_Cell1 <- fgsea(pathways = c5BP_pathways,
                  stats = Cell1_ranks,
                  minSize  = 15,
                  maxSize  = 500,
                  nperm = 1000)
#fgsea_c5BP_Cell2 <- fgsea(pathways = c5BP_pathways,
#                  stats = Cell2_ranks,
#                  minSize  = 15,
#                  maxSize  = 500,
#                  nperm = 1000)

fgsea_c7IM_Cell1 <- fgsea(pathways = c7IM_pathways,
                  stats = Cell1_ranks,
                  minSize  = 15,
                  maxSize  = 500,
                  nperm = 1000)

#fgsea_c7IM_Cell2 <- fgsea(pathways = c7IM_pathways,
#                  stats = Cell2_ranks,
#                  minSize  = 15,
#                  maxSize  = 500,
#                  nperm = 1000)

fgsea_Th2GO_Cell1 <- fgsea(pathways = Th2_GO_pathway,
                  stats = Cell1_ranks,
                  minSize  = 15,
                  maxSize  = 500,
                  nperm = 1000)

fgsea_Th2_Cell1 <- fgsea(pathways = Th2_pathway,
                  stats = Cell1_ranks,
                  minSize  = 15,
                  maxSize  = 500,
                  nperm = 1000)

fgsea_AsthmaSNP_Cell1 <- fgsea(pathways = SNP_asthma_pathway,
                  stats = Cell1_ranks,
                  minSize  = 15,
                  maxSize  = 500,
                  nperm = 1000)
```

Tidy up the results and then show in nice table

```{r}
tidy_fgsea_H_Cell1 <- fgsea_H_Cell1 %>%
  as_tibble() %>%
  arrange(desc(NES))
tidy_fgsea_H_Cell1 %>%
  dplyr::select(-leadingEdge, -ES, -nMoreExtreme) %>%
  arrange(padj) %>%
  DT::datatable()

datatable_data <- as.data.frame(tidy_fgsea_H_Cell1) # Extract the data from the DT::datatable
wb <- createWorkbook() # Create a new Excel workbook
addWorksheet(wb, "DataTable") # Add a worksheet to the workbook
writeDataTable(wb, "DataTable", datatable_data) # Write the data from the DT::datatable to the Excel worksheet
saveWorkbook(wb, "GSEA/GSEA_LUVA_Hpathway-full.xlsx") # Save the workbook to a file

#tidy_fgsea_H_Cell2 <- fgsea_H_Cell2 %>%
#  as_tibble() %>%
#  arrange(desc(NES))
#tidy_fgsea_H_Cell2 %>%
#  dplyr::select(-leadingEdge, -ES, -nMoreExtreme) %>%
#  arrange(padj) %>%
#  DT::datatable()

#datatable_data <- as.data.frame(tidy_fgsea_H_Cell2) # Extract the data from the DT::datatable
#wb <- createWorkbook() # Create a new Excel workbook
#addWorksheet(wb, "DataTable") # Add a worksheet to the workbook
#writeDataTable(wb, "DataTable", datatable_data) # Write the data from the DT::datatable to the Excel worksheet
#saveWorkbook(wb, "./analyse/Results/GSEA/GSEA_LUVA_Hpathway-full.xlsx") # Save the workbook to a file
```

```{r}
tidy_fgsea_c2CP_Cell1 <- fgsea_c2CP_Cell1 %>%
  as_tibble() %>%
  arrange(desc(NES))
tidy_fgsea_c2CP_Cell1 %>%
  dplyr::select(-leadingEdge, -ES, -nMoreExtreme) %>%
  arrange(padj) %>%
  DT::datatable()

datatable_data <- as.data.frame(tidy_fgsea_c2CP_Cell1) # Extract the data from the DT::datatable
wb <- createWorkbook() # Create a new Excel workbook
addWorksheet(wb, "DataTable") # Add a worksheet to the workbook
writeDataTable(wb, "DataTable", datatable_data) # Write the data from the DT::datatable to the Excel worksheet
saveWorkbook(wb, "./GSEA/GSEA_LUVA_c2CPpathway-full.xlsx") # Save the workbook to a file

#tidy_fgsea_c2CP_Cell2 <- fgsea_c2CP_Cell2 %>%
#  as_tibble() %>%
#  arrange(desc(NES))
#tidy_fgsea_c2CP_Cell2 %>%
#  dplyr::select(-leadingEdge, -ES, -nMoreExtreme) %>%
#  arrange(padj) %>%
#  DT::datatable()

#datatable_data <- as.data.frame(tidy_fgsea_c2CP_Cell2) # Extract the data from the DT::datatable
#wb <- createWorkbook() # Create a new Excel workbook
#addWorksheet(wb, "DataTable") # Add a worksheet to the workbook
#writeDataTable(wb, "DataTable", datatable_data) # Write the data from the DT::datatable to the Excel worksheet
#saveWorkbook(wb, "./analyse/Results/GSEA/GSEA_LUVA_c2CPpathway-full.xlsx") # Save the workbook to a file

tidy_fgsea_c5BP_Cell1 <- fgsea_c5BP_Cell1 %>%
  as_tibble() %>%
  arrange(desc(NES))
tidy_fgsea_c5BP_Cell1 %>%
  dplyr::select(-leadingEdge, -ES, -nMoreExtreme) %>%
  arrange(padj) %>%
  DT::datatable()

datatable_data <- as.data.frame(tidy_fgsea_c5BP_Cell1) # Extract the data from the DT::datatable
wb <- createWorkbook() # Create a new Excel workbook
addWorksheet(wb, "DataTable") # Add a worksheet to the workbook
writeDataTable(wb, "DataTable", datatable_data) # Write the data from the DT::datatable to the Excel worksheet
saveWorkbook(wb, "./GSEA/GSEA_LUVA_c5BPpathway-full.xlsx") # Save the workbook to a file

#tidy_fgsea_c5BP_Cell2 <- fgsea_c5BP_Cell2 %>%
#  as_tibble() %>%
#  arrange(desc(NES))
#tidy_fgsea_c5BP_Cell2 %>%
#  dplyr::select(-leadingEdge, -ES, -nMoreExtreme) %>%
#  arrange(padj) %>%
#  DT::datatable()

#datatable_data <- as.data.frame(tidy_fgsea_c5BP_Cell2) # Extract the data from the DT::datatable
#wb <- createWorkbook() # Create a new Excel workbook
#addWorksheet(wb, "DataTable") # Add a worksheet to the workbook
#writeDataTable(wb, "DataTable", datatable_data) # Write the data from the DT::datatable to the Excel worksheet
#saveWorkbook(wb, "./analyse/Results/GSEA/GSEA_LUVA_c5BPpathway-full.xlsx") # Save the workbook to a file

###Added by Carli
tidy_fgsea_c7IM_Cell1 <- fgsea_c7IM_Cell1 %>%
  as_tibble() %>%
  arrange(desc(NES))
tidy_fgsea_c7IM_Cell1 %>%
  dplyr::select(-leadingEdge, -ES, -nMoreExtreme) %>%
  arrange(padj) %>%
  DT::datatable()

datatable_data <- as.data.frame(tidy_fgsea_c7IM_Cell1) # Extract the data from the DT::datatable
wb <- createWorkbook() # Create a new Excel workbook
addWorksheet(wb, "DataTable") # Add a worksheet to the workbook
writeDataTable(wb, "DataTable", datatable_data) # Write the data from the DT::datatable to the Excel worksheet
saveWorkbook(wb, "./GSEA/GSEA_LUVA_C7IMpathway-full.xlsx") # Save the workbook to a file




tidy_fgsea_Th2GO_Cell1 <- fgsea_Th2GO_Cell1 %>%
  as_tibble() %>%
  arrange(desc(NES))
tidy_fgsea_Th2GO_Cell1 %>%
  dplyr::select(-leadingEdge, -ES, -nMoreExtreme) %>%
  arrange(padj) %>%
  DT::datatable()

datatable_data <- as.data.frame(tidy_fgsea_Th2GO_Cell1) # Extract the data from the DT::datatable
wb <- createWorkbook() # Create a new Excel workbook
addWorksheet(wb, "DataTable") # Add a worksheet to the workbook
writeDataTable(wb, "DataTable", datatable_data) # Write the data from the DT::datatable to the Excel worksheet
saveWorkbook(wb, "./GSEA/GSEA_LUVA_Th2GOpathway-full.xlsx") # Save the workbook to a file




tidy_fgsea_Th2_Cell1 <- fgsea_Th2_Cell1 %>%
  as_tibble() %>%
  arrange(desc(NES))
tidy_fgsea_Th2_Cell1 %>%
  dplyr::select(-leadingEdge, -ES, -nMoreExtreme) %>%
  arrange(padj) %>%
  DT::datatable()

datatable_data <- as.data.frame(tidy_fgsea_Th2_Cell1) # Extract the data from the DT::datatable
wb <- createWorkbook() # Create a new Excel workbook
addWorksheet(wb, "DataTable") # Add a worksheet to the workbook
writeDataTable(wb, "DataTable", datatable_data) # Write the data from the DT::datatable to the Excel worksheet
saveWorkbook(wb, "./GSEA/GSEA_LUVA_Th2pathway-full.xlsx") # Save the workbook to a file




tidy_fgsea_AsthmaSNP_Cell1 <- fgsea_AsthmaSNP_Cell1 %>%
  as_tibble() %>%
  arrange(desc(NES))
tidy_fgsea_AsthmaSNP_Cell1 %>%
  dplyr::select(-leadingEdge, -ES, -nMoreExtreme) %>%
  arrange(padj) %>%
  DT::datatable()

datatable_data <- as.data.frame(tidy_fgsea_AsthmaSNP_Cell1) # Extract the data from the DT::datatable
wb <- createWorkbook() # Create a new Excel workbook
addWorksheet(wb, "DataTable") # Add a worksheet to the workbook
writeDataTable(wb, "DataTable", datatable_data) # Write the data from the DT::datatable to the Excel worksheet
saveWorkbook(wb, "./GSEA/GSEA_LUVA_AsthmaSNPpathway-full.xlsx") # Save the workbook to a file
```

For H:

```{r}
# Plot Enrichment Scores
filtered_fgsea_H_Cell1 <- tidy_fgsea_H_Cell1 %>% filter(padj<0.05)
filtered_fgsea_H_Cell1$pathway <- sub("HALLMARK_","",filtered_fgsea_H_Cell1$pathway)
ggplot(filtered_fgsea_H_Cell1, aes(reorder(pathway, NES), NES)) +
  geom_col(fill='dodgerblue') +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="Molecular Hallmarks Pathways GSEA coculture effect on sensory neurons") +
  theme_minimal()

filtered_fgsea_H_Cell2 <- tidy_fgsea_H_Cell2 %>% filter(padj<0.05)
filtered_fgsea_H_Cell2$pathway <- sub("HALLMARK_","",filtered_fgsea_H_Cell2$pathway)
ggplot(filtered_fgsea_H_Cell2, aes(reorder(pathway, NES), NES)) +
  geom_col(fill='dodgerblue') +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="Molecular Hallmarks Pathways GSEA coculture effect on mast cells") +
  theme_minimal()
```

For c2CP:

```{r}
collapsed_c2CP_Cell1 <- collapsePathways(fgsea_c2CP_Cell1[order(pval)][padj < 0.05],
                                         c2CP_pathways,
                                         Cell1_ranks)
main_c2CP_Cell1 <- fgsea_c2CP_Cell1[pathway %in%  
                                    collapsed_c2CP_Cell1$mainPathways][order(-NES), pathway]
main_res_c2CP_Cell1 <- fgsea_c2CP_Cell1[fgsea_c2CP_Cell1$pathway %in% main_c2CP_Cell1] 
main_res_c2CP_Cell1$pathway <- sub("^REACTOME_|^WP_", "",main_res_c2CP_Cell1$pathway)

num_top_pathways <- 50 # Choose the number of top pathways to display

# Select the top pathways based on NES
top_main_res_c2CP_Cell1 <- main_res_c2CP_Cell1 %>%
  top_n(num_top_pathways, wt = NES)

ggplot(top_main_res_c2CP_Cell1, aes(reorder(pathway, NES), NES)) +
  geom_col(fill='dodgerblue') +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="CP Collapsed Pathways GSEA coculture effect on sensory neurons") + 
  theme_minimal()

collapsed_c2CP_Cell2 <- collapsePathways(fgsea_c2CP_Cell2[order(pval)][padj < 0.05],
                                         c2CP_pathways,
                                         Cell2_ranks)
main_c2CP_Cell2 <- fgsea_c2CP_Cell2[pathway %in% 
                                    collapsed_c2CP_Cell2$mainPathways][order(-NES), pathway]
main_res_c2CP_Cell2 <- fgsea_c2CP_Cell2[fgsea_c2CP_Cell2$pathway %in% main_c2CP_Cell2] 
main_res_c2CP_Cell2$pathway <- sub("^REACTOME_|^WP_", "",main_res_c2CP_Cell2$pathway)

num_top_pathways <- 25 # Choose the number of top pathways to display

# Select the top pathways based on NES
top_main_res_c2CP_Cell2 <- main_res_c2CP_Cell2 %>%
  top_n(num_top_pathways, wt = NES)

ggplot(top_main_res_c2CP_Cell2, aes(reorder(pathway, NES), NES)) +
  geom_col(fill='dodgerblue') +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="CP Collapsed Pathways GSEA coculture effect on mast cell") + 
  theme_minimal()
```

For c5BP:

```{r}
collapsed_c5BP_Cell1 <- collapsePathways(fgsea_c5BP_Cell1[order(pval)][padj < 0.02],
                                         c5BP_pathways,
                                         Cell1_ranks)
main_c5BP_Cell1 <- fgsea_c5BP_Cell1[pathway %in% collapsed_c5BP_Cell1$mainPathways][order(-NES), pathway]
main_res_c5BP_Cell1 <- fgsea_c5BP_Cell1[fgsea_c5BP_Cell1$pathway %in% main_c5BP_Cell1] 
main_res_c5BP_Cell1$pathway <- sub("GOBP_","",main_res_c5BP_Cell1$pathway)

num_top_pathways <- 25 # Choose the number of top pathways to display

# Select the top pathways based on NES
top_main_res_c5BP_Cell1 <- main_res_c5BP_Cell1 %>%
  top_n(num_top_pathways, wt = NES)

ggplot(top_main_res_c5BP_Cell1, aes(reorder(pathway, NES), NES)) +
  geom_col(fill='dodgerblue') +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="GO BP Collapsed Pathways GSEA coculture effect on sensory neurons") + 
  theme_minimal()

collapsed_c5BP_Cell2 <- collapsePathways(fgsea_c5BP_Cell2[order(pval)][padj < 0.05],
                                         c5BP_pathways,
                                         Cell2_ranks)
main_c5BP_Cell2 <- fgsea_c5BP_Cell2[pathway %in% 
                                    collapsed_c5BP_Cell2$mainPathways][order(-NES), pathway]
main_res_c5BP_Cell2 <- fgsea_c5BP_Cell2[fgsea_c5BP_Cell2$pathway %in% main_c5BP_Cell2] 
main_res_c5BP_Cell2$pathway <- sub("GOBP_","",main_res_c5BP_Cell2$pathway)

num_top_pathways <- 100 # Choose the number of top pathways to display

# Select the top pathways based on NES
top_main_res_c5BP_Cell2 <- main_res_c5BP_Cell2 %>%
  top_n(num_top_pathways, wt = NES)


ggplot(top_main_res_c5BP_Cell2, aes(reorder(pathway, NES), NES)) +
  geom_col(fill='dodgerblue') +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="GO BP Collapsed Pathways GSEA coculture effect on mast cell") + 
  theme_minimal()
```

For c7IM:

```{r}
collapsed_c7IM_Cell1 <- collapsePathways(fgsea_c7IM_Cell1[order(pval)][padj < 0.02],
                                         c7IM_pathways,
                                         Cell1_ranks)
main_c7IM_Cell1 <- fgsea_c7IM_Cell1[pathway %in% collapsed_c7IM_Cell1$mainPathways][order(-NES), pathway]
main_res_c7IM_Cell1 <- fgsea_c7IM_Cell1[fgsea_c7IM_Cell1$pathway %in% main_c7IM_Cell1] 
main_res_c7IM_Cell1$pathway <- sub("GOBP_","",main_res_c7IM_Cell1$pathway)

num_top_pathways <- 25 # Choose the number of top pathways to display

# Select the top pathways based on NES
top_main_res_c7IM_Cell1 <- main_res_c7IM_Cell1 %>%
  top_n(num_top_pathways, wt = NES)

ggplot(top_main_res_c7IM_Cell1, aes(reorder(pathway, NES), NES)) +
  geom_col(fill='dodgerblue') +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="GO BP Collapsed Pathways GSEA coculture effect on sensory neurons") + 
  theme_minimal()

collapsed_c7IM_Cell2 <- collapsePathways(fgsea_c7IM_Cell2[order(pval)][padj < 0.05],
                                         c7IM_pathways,
                                         Cell2_ranks)
main_c7IM_Cell2 <- fgsea_c7IM_Cell2[pathway %in% 
                                    collapsed_c7IM_Cell2$mainPathways][order(-NES), pathway]
main_res_c7IM_Cell2 <- fgsea_c7IM_Cell2[fgsea_c7IM_Cell2$pathway %in% main_c7IM_Cell2] 
main_res_c7IM_Cell2$pathway <- sub("GOBP_","",main_res_c7IM_Cell2$pathway)

num_top_pathways <- 100 # Choose the number of top pathways to display

# Select the top pathways based on NES
top_main_res_c7IM_Cell2 <- main_res_c7IM_Cell2 %>%
  top_n(num_top_pathways, wt = NES)


ggplot(top_main_res_c7IM_Cell2, aes(reorder(pathway, NES), NES)) +
  geom_col(fill='dodgerblue') +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="GO BP Collapsed Pathways GSEA coculture effect on mast cell") + 
  theme_minimal()
```

Alternatives for GO BP Collapse Pathways #did not run this!

```{r}
top50 <- head(tidy_fgsea_c5BP_Cell1[order(tidy_fgsea_c5BP_Cell1$NES, decreasing=TRUE),], n=50)

ggplot(top50, aes(reorder(pathway, NES), NES)) +
  geom_col(fill='dodgerblue') +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="Molecular Hallmarks Pathways GSEA coculture effect on sensory neurons") +
  theme_minimal()

collapsed_c5BP_Cell1 <- collapsePathways(fgsea_c5BP_Cell1[order(pval)][padj < 0.01],
                                         c5BP_pathways,
                                         Cell1_ranks)
main_c5BP_Cell1 <- fgsea_c5BP_Cell1[pathway %in% collapsed_c5BP_Cell1$mainPathways][order(-NES), pathway]
main_res_c5BP_Cell1 <- fgsea_c5BP_Cell1[fgsea_c5BP_Cell1$pathway %in% main_c5BP_Cell1]
tidy_fgsea_c5BP_Cell1 <- main_res_c5BP_Cell1 %>%
  as_tibble() %>%
  arrange(desc(NES))
tidy_fgsea_c5BP_Cell1 %>%
  dplyr::select(-leadingEdge, -ES, -nMoreExtreme) %>%
  arrange(padj) %>%
  DT::datatable() 

tidy_fgsea_c5BP_Cell1$pathway <- sub("GOBP_","",tidy_fgsea_c5BP_Cell1$pathway)

filtered_fgsea_c5BP_Cell1 <- tidy_fgsea_c5BP_Cell1 %>% filter(padj<0.05) 
top50 <- head(filtered_fgsea_c5BP_Cell1[order(filtered_fgsea_c5BP_Cell1$NES, decreasing=TRUE),], n=50)

ggplot(top50, aes(reorder(pathway, NES), NES)) +
  geom_col(fill='dodgerblue') +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="GO BP Collapsed Pathways GSEA coculture effect on sensory neurons") +
  theme_minimal()
```
